#if !canImport(ObjectiveC)
import XCTest

extension Test_ExampleModel_Table {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Test_ExampleModel_Table = [
        ("testName", testName),
    ]
}

extension Test_ModelOperations {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Test_ModelOperations = [
        ("testUpsert", testUpsert),
    ]
}

extension Test_NullableString_Column {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Test_NullableString_Column = [
        ("testNullableString", testNullableString),
    ]
}

extension Test_String_Column {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Test_String_Column = [
        ("testString", testString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Test_ExampleModel_Table.__allTests__Test_ExampleModel_Table),
        testCase(Test_ModelOperations.__allTests__Test_ModelOperations),
        testCase(Test_NullableString_Column.__allTests__Test_NullableString_Column),
        testCase(Test_String_Column.__allTests__Test_String_Column),
    ]
}
#endif
