#if !canImport(ObjectiveC)
import XCTest

extension Test_ExampleModel_Schema {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Test_ExampleModel_Schema = [
        ("testName", testName),
    ]
}

extension Test_KeyValue_ReadWrite {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Test_KeyValue_ReadWrite = [
        ("testBool", testBool),
        ("testNullableBool", testNullableBool),
    ]
}

extension Test_NullableString_Column {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Test_NullableString_Column = [
        ("testNullableString", testNullableString),
    ]
}

extension Test_String_Column {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Test_String_Column = [
        ("testString", testString),
    ]
}

extension Test_Upsert_ModelOperations {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Test_Upsert_ModelOperations = [
        ("testUpsert", testUpsert),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Test_ExampleModel_Schema.__allTests__Test_ExampleModel_Schema),
        testCase(Test_KeyValue_ReadWrite.__allTests__Test_KeyValue_ReadWrite),
        testCase(Test_NullableString_Column.__allTests__Test_NullableString_Column),
        testCase(Test_String_Column.__allTests__Test_String_Column),
        testCase(Test_Upsert_ModelOperations.__allTests__Test_Upsert_ModelOperations),
    ]
}
#endif
